name: Deploy Seguro com Chaves Protegidas

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Puxar o código do repositório
        uses: actions/checkout@v4

      - name: Injetar as chaves de API (vindas dos Secrets do GitHub)
        run: |
          chmod +x injeta-chaves.sh
          ./injeta-chaves.sh
        env:
          APIKEY_TMDB: ${{ secrets.APIKEY_TMDB }}
          APIKEY_OMDB: ${{ secrets.APIKEY_OMDB }}

      - name: Configurar as Pages do GitHub
        uses: actions/configure-pages@v4

      - name: Fazer upload dos arquivos do site
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Publicar no GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4